### ISSUE TITLE
why POST with no payload is not allowed?

### ISSUE THREAD

**Issue by geekybaiyi** [ardielle/ardielle-go#22]
hi ,

question on https://github.com/ardielle/ardielle-go/blob/master/rdl/parser.go#L2053

the parser doesn't allow empty body with POST. however sometimes it is required. 
for example:  
1. I want the resource to sync with some external source:  POST /v1/projects/:projId/sync
2. Or I want to kick off some lengthy action and the resource already have enough information to operation it, I could do POST /v1/projects/:projId/someAction

reference : http://stackoverflow.com/questions/4191593/is-it-considered-bad-practice-to-perform-http-post-without-entity-body

Do you think this restriction on RDL parser can be revised ? 

thx,
Baiyi

**Comment by boynton** [comment]
Need to check that all the code generators can handle it, but it conceptually seems reasonable, if not very REST-like.

**Comment by boynton** [comment]
Generated code seems ok.
