### ISSUE TITLE
Performance/Memory issues with rdl.Validate when FullValidation enabled

### ISSUE THREAD

**Issue by evantorrie** [ardielle/ardielle-go#26]
The current go implementation of `rdl.Validate` calls `NewTypeRegistry(schema)` on every invocation.  For a complex schema, this is a costly operation.

https://github.com/ardielle/ardielle-go/blob/0e40fcc616a01e6cd32f526a866ef18c762df270/rdl/validator.go#L46

This becomes apparent in go when unmarshalling large objects with nested structs containing a lot of "derived-from-String" types.

In tests, I've found that code which would just cache the TypeRegistry per schema when calling `schema.Build()` and then use that in a `rdl.Validate2()` style call which can accept a preconstructed TypeRegistry gives a close to 10x improvement on JSON unmarshalling speed.

**Comment by boynton** [comment]
Thanks, good find. Will fix that. Or... you can if you want :-)

**Comment by evantorrie** [comment]
I have a fix which involves exposing a `Validator` object -- and then having the code generator generate an instance of that at schema build time.   I'll submit a PR, but I don't know enough details about the implementations in other languages to know whether it's the best way to solve this issue.

**Comment by boynton** [comment]
Well, Fixing it behind the scenes would be best, it is just a performance optimization for the Go library, other libraries have different ways to deal with it, so don't worry about those just yet. If you want to just send me a sketch (or pointer to your changes) I can integrate it, I just thought you were closer to it, having done the performance comparison already.

**Comment by evantorrie** [comment]
I changed it to use a transparent cache - no change to the exposed API.

Take a look at #29

**Comment by boynton** [comment]
Fixed in Release 1.4.13, PR #29
