### ISSUE TITLE
Code panic when using RDL files with case-sensitive base types

### ISSUE THREAD

**Issue by evantorrie** [ardielle/ardielle-go#27]
This change https://github.com/ardielle/ardielle-go/commit/af82e721d059573ae43adeffaf54f1a59f555b19#diff-c47cfc4879d59b2c3268af73178decfb added a number of string comparisons for base types that rely on the base type having a specific capitalization.

However, RDL types are defined to be case-insensitive see _Note: all type names in RDL are case-insensitive. Capitalized types are used in this document._ from https://ardielle.github.io/

The net result is that some of our older RDL generated schema.go code now panics when trying to build the schema, e.g.

```go
sb := rdl.NewSchemaBuilder("model")

tEvent := rdl.NewStructTypeBuilder("struct", "Event")
tEvent.Field("type", "EventType", false, nil, "")
tEvent.Field("level", "Int32", false, nil, "")
sb.AddType(tEvent.Build())
```

**Comment by evantorrie** [comment]
Tests and a somewhat heavy-handed fix in #28.  Comparing case-sensitive strings in parsing code seems fraught with problems - should we move to a canonical form (constants?) to represent these base types?

**Comment by boynton** [comment]
Well, case insensitivity seems important, problem is there isn't a good way to handle canonical form then (the canonical form *should* follow normal CamelCase conventions, but that is harder than simply doing case folding before compare. I'm more interested in approving this to fix the problem, the entire parser needs some cleanup, which I'd like to do before the next major release version.

**Comment by evantorrie** [comment]
Closing this particular issue with merge of #28
