### ISSUE TITLE
Support ExtendedOption in Identifier of EnumTypeSpec

### ISSUE THREAD

**Issue by joejoe321321** [ardielle/ardielle-go#34]
https://ardielle.github.io/syntax.xhtml#Identifier
Now Identifier of Enum in RDL is defined as Name.
Is it possible to support ExtendedOption in Identifier?

We want to construct alias for each Enum element.
It seems ExtendedOption can solve our problem.

example:

type Enum Animal {
    CAT (x_intValue="0"),
    DOG (x_intValue="1"),
    BIRD (x_intValue="2")
}

Thank you.

**Comment by boynton** [comment]
This may require a change in rdl.rdl, which would get deferred to the next major release, as it is not strictly compatible.

**Comment by boynton** [comment]
It turns out an upward compatible change makes annotations possible (the syntax diagram is not up to date, comments per elements are already supported, so the type of an enum element is EnumElementDef, not Identifier, where a new optional field is easily added).
