### ISSUE TITLE
Building the RDL command

### ISSUE THREAD

**Issue by patc888** [ardielle/ardielle-go#46]
Not being a go expert, can you add a few lines on the steps to build the rdl command and the plug-ins on different platforms (e.g. macos and linux).

**Comment by boynton** [comment]
On a Mac:=, install golang v1.8+, then:

export GOPATH=$HOME/go
mkdir -p $GOPATH/bin
go get github.com/ardielle/ardielle-tools/...

This installs all the executables in $GOPATH/bin.

Then, to cross-compile for linux:

cd $HOME/go/src/github.com/ardielle/ardielle-tools
GOOS=linux GOARCH=amd64 go build -o /tmp/linux_bin/rdl github.com/ardielle/ardielle-tools/rdl
GOOS=linux GOARCH=amd64 go build -o /tmp/linux_bin/rdl-gen-swagger github.com/ardielle/ardielle-tools/rdl-plugins/swagger/rdl-gen-swagger

and so on for each executable.
